version: '3.8'

services:
  postgres:
    image: postgres:17.6
    container_name: dl_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  rabbitmq:
    image: rabbitmq:4.1.4-management
    container_name: dl_rabbitmq
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
#  app:
#    build: .
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db
#      - rabbitmq
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: postgres
#      SPRING_RABBITMQ_HOST: rabbitmq

  loki:
    image: grafana/loki:2.8.2
    container_name: dl_loki
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
  tempo:
    image: grafana/tempo:1.6.0
    container_name: dl_tempo
    command: -config.file=/etc/tempo/local-config.yaml
    ports:
      - "3200:3200"
    volumes:
      - ./tempo-config.yaml:/etc/tempo/local-config.yaml
  prometheus:
    image: prom/prometheus:v2.53.1
    container_name: dl_prometheus
    volumes:
      - ./prometheus-config.yaml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    depends_on:
      - postgres
      - rabbitmq
      - loki
      - tempo
  grafana:
    image: grafana/grafana:10.5.2
    container_name: dl_grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-piechart-panel,grafana-simple-json-datasource
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - loki
      - tempo

volumes:
  postgres_data:
    name: dl_postgres_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/postgres
  rabbitmq_data:
    name: dl_rabbitmq_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/rabbitmq

  loki_data:
    name: dl_loki_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/grafana/loki
  tempo_data:
    name: dl_tempo_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/grafana/tempo
  prometheus_data:
    name: dl_prometheus_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/grafana/prometheus
  grafana_data:
    name: dl_grafana_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/grafana/grafana

networks:
  dl_network:
    driver: bridge