spring:
  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
  rabbitmq:
    host: ${rabbit.host}
    port: ${rabbit.port}
    username: ${rabbit.username}
    password: ${rabbit.password}