spring:
  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}

authorization:
  keyName: ${api.key.name}
  authValue: ${api.key.value}
